/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  product?: ProductReference;
  name?: string;
  rating?: number;
  comment?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCustomerId?: string;
  stripePaymentIntentId?: string;
  stripeCheckoutSessionId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  products?: Array<{
    product?: ProductReference;
    quantity?: number;
    _key: string;
  }>;
  totalPrice?: number;
  currency?: string;
  shipping?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?:
    | "pending"
    | "processing"
    | "paid"
    | "shipped"
    | "out_for_delivery"
    | "delivered"
    | "cancelled";
  isHidden?: boolean;
  orderDate?: string;
};

export type CategoryReference = {
  _id: string;
  name: string | null;
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  price?: number;
  discount?: number;
  status?: Array<"hot" | "sale" | "new">;
  category?: CategoryReference;
  brand?: BrandReference;
  stock?: number;
  Reviews?: Array<Review>;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type BlockCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blockCategory";
};

export type BlogType = {
  _id: string;
  _type: "blogType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogCategories?: Array<
    {
      _key: string;
    } & BlockCategoryReference
  >;
  publishedAt?: string;
  islatest?: boolean;
  body?: BlockContent;
};

export type BlockCategory = {
  _id: string;
  _type: "blockCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Address = {
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  address?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  createdAt?: string;
  isDefault?: boolean;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  range?: number;
  featured?: boolean;
  productCount?: number;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Collection = {
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProductReference
  | Review
  | SanityImageAssetReference
  | BlockContent
  | Order
  | CategoryReference
  | BrandReference
  | Product
  | Brand
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | AuthorReference
  | BlockCategoryReference
  | BlogType
  | BlockCategory
  | Author
  | Address
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/query.ts
// Variable: BRANDS_QUERY
// Query: *[_type== 'brand'] | order(name asc)
export type BRANDS_QUERY_RESULT = Array<{
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;

// Source: sanity/queries/query.ts
// Variable: LATEST_BLOG_QUERY
// Query: *[_type == "blogType" && islatest == true]        | order(publishedAt desc)[0...5] {            title,            slug,            mainImage,            publishedAt,            blogCategories[]->{            title            }        }
export type LATEST_BLOG_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  publishedAt: string | null;
  blogCategories: Array<{
    title: string | null;
  }> | null;
}>;

// Source: sanity/queries/query.ts
// Variable: ALL_BLOGS_QUERY
// Query: *[_type == "blogType"] | order(publishedAt desc) {    ...,     blogCategories[]->{        title      }    }
export type ALL_BLOGS_QUERY_RESULT = Array<{
  _id: string;
  _type: "blogType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogCategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  islatest?: boolean;
  body?: BlockContent;
}>;

// Source: sanity/queries/query.ts
// Variable: SINGLE_BLOG_QUERY
// Query: *[_type == "blogType" && slug.current == $slug] | order(publishedAt desc)[0]{    ...,    author->{        name,        image    },    blogCategories[]->{        title,        "slug": slug.current        }}
export type SINGLE_BLOG_QUERY_RESULT = {
  _id: string;
  _type: "blogType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author: {
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogCategories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  publishedAt?: string;
  islatest?: boolean;
  body?: BlockContent;
} ;

// Source: sanity/queries/query.ts
// Variable: BLOG_CATEGORIES_QUERY
// Query: *[_type == "blogType"]{    blogCategories[]->{    ...    }    }
export type BLOG_CATEGORIES_QUERY_RESULT = Array<{
  blogCategories: Array<{
    _id: string;
    _type: "blockCategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    description?: string;
    slug?: Slug;
  }> ;
}>;

// Source: sanity/queries/query.ts
// Variable: BLOG_OTHER_CATEGORIES_QUERY
// Query: *[    _type == "blogType" && defined(slug.current) && slug.current != $slug] | order(publishedAt desc)[0...$quantity] {    ...,    publishedAt,    title,    mainImage,    slug,    author->{    name,    image},categories[]->{title,"slug": slug.current}}
export type BLOG_OTHER_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  _type: "blogType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  slug: Slug | null;
  author: {
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  blogCategories?: Array<
    {
      _key: string;
    } & BlockCategoryReference
  >;
  publishedAt: string | null;
  islatest?: boolean;
  body?: BlockContent;
  categories: null;
}>;

// Source: sanity/queries/query.ts
// Variable: DEAL_PRODUCT_QUERY
// Query: *[_type == "product" && "hot" in status]| order(name asc){    ...,    "category": category->{    _id,    name},        }
export type DEAL_PRODUCT_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  price?: number;
  discount?: number;
  status?: Array<"hot" | "new" | "sale">;
  category: {
    _id: string;
    name: string | null;
  } | null;
  brand?: BrandReference;
  stock?: number;
  Reviews?: Array<Review>;
}>;

// Source: sanity/queries/query.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug] | order(name asc) [0]{    ...,"category": category->name,        }
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  price?: number;
  discount?: number;
  status?: Array<"hot" | "new" | "sale">;
  category: string | null;
  brand?: BrandReference;
  stock?: number ;
  Reviews: Array<Review>;
} ;

// Source: sanity/queries/query.ts
// Variable: BRAND_PRODUCT_DETAILS_QUERY
// Query: *[_type == "product" && slug.current == $slug] | order(name asc)[0]{    "brandName" : brand->title,        }
export type BRAND_PRODUCT_DETAILS_QUERY_RESULT = {
  brandName?: string ;
} ;

// Source: sanity/queries/query.ts
// Variable: ORDERS_BY_USER_QUERY
// Query: *[_type == "order" && clerkUserId == $userId && !isHidden]| order(orderDate desc) {  ...,  products[]{    _key,    quantity,    product->{      _id,      _type,      name,      slug,      description,      images,      price,      discount,      status,      stock    }  }}
export type ORDERS_BY_USER_QUERY_RESULT = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCustomerId?: string;
  stripePaymentIntentId?: string;
  stripeCheckoutSessionId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  products: Array<{
    _key: string;
    quantity: number | null;
    product: {
      _id: string;
      _type: "product";
      name: string | null;
      slug: Slug | null;
      description: string | null;
      images: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }> | null;
      price: number ;
      discount: number | null;
      status: Array<"hot" | "new" | "sale"> | null;
      stock: number | null;
    } | null;
  }> | null;
  totalPrice?: number;
  currency?: string;
  shipping?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?:
    | "cancelled"
    | "delivered"
    | "out_for_delivery"
    | "paid"
    | "pending"
    | "processing"
    | "shipped";
  isHidden?: boolean;
  orderDate?: string;
}>;

// Source: sanity/queries/query.ts
// Variable: SEARCH_PRODUCTS_QUERY
// Query: *[_type == "product" && name match $searchTerm + "*"] | order(name asc) [0...10] {        _id,        name,        slug,        price,        images,        "category": category->name    }
export type SEARCH_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discount: number | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  category: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type== 'brand'] | order(name asc)": BRANDS_QUERY_RESULT;
    ' *[_type == "blogType" && islatest == true]\n        | order(publishedAt desc)[0...5] {\n            title,\n            slug,\n            mainImage,\n            publishedAt,\n            blogCategories[]->{\n            title\n            }\n        }': LATEST_BLOG_QUERY_RESULT;
    '*[_type == "blogType"] | order(publishedAt desc) {\n    ..., \n    blogCategories[]->{\n        title  \n    }\n    }\n': ALL_BLOGS_QUERY_RESULT;
    '*[_type == "blogType" && slug.current == $slug] | order(publishedAt desc)[0]{\n    ...,\n    author->{\n        name,\n        image\n    },\n    blogCategories[]->{\n        title,\n        "slug": slug.current\n        }}': SINGLE_BLOG_QUERY_RESULT;
    '*[_type == "blogType"]{\n    blogCategories[]->{\n    ...\n    }\n    }': BLOG_CATEGORIES_QUERY_RESULT;
    '*[\n    _type == "blogType" && defined(slug.current) && slug.current != $slug] | order(publishedAt desc)[0...$quantity] {\n    ...,\n    publishedAt,\n    title,\n    mainImage,\n    slug,\n    author->{\n    name,\n    image\n},\ncategories[]->{\ntitle,\n"slug": slug.current\n}\n}': BLOG_OTHER_CATEGORIES_QUERY_RESULT;
    '*[_type == "product" && "hot" in status]\n| order(name asc){\n    ...,\n    "category": category->{\n    _id,\n    name},\n    \n    }': DEAL_PRODUCT_QUERY_RESULT;
    '*[_type == "product" && slug.current == $slug] | order(name asc) [0]{\n    ...,"category": category->name,\n    \n    }': PRODUCT_BY_SLUG_QUERY_RESULT;
    '*[_type == "product" && slug.current == $slug] | order(name asc)[0]{\n    "brandName" : brand->title,\n    \n    }': BRAND_PRODUCT_DETAILS_QUERY_RESULT;
    '\n*[_type == "order" && clerkUserId == $userId && !isHidden]\n| order(orderDate desc) {\n  ...,\n  products[]{\n    _key,\n    quantity,\n    product->{\n      _id,\n      _type,\n      name,\n      slug,\n      description,\n      images,\n      price,\n      discount,\n      status,\n      stock\n    }\n  }\n}\n': ORDERS_BY_USER_QUERY_RESULT;
    '*[_type == "product" && name match $searchTerm + "*"] | order(name asc) [0...10] {\n        _id,\n        name,\n        slug,\n        price,\n        images,\n        "category": category->name\n    }': SEARCH_PRODUCTS_QUERY_RESULT;
  }
}
